### PR TITLE
Reindex packages in repo

### LINKED ISSUE #105: ReIndex all packages in whole repo
Maybe some bug or unexpected requirement scenarios make 'index.yml' broken or incorrect.
We need foreach all packages and calculate a correct 'index.yml'.

### LINKED ISSUE #115: Refactoring to avoid code duplication
Let's extract a class for obtaining date in specified format and class for obtaining empty index as it would be helpful for using in `Helm.Asto#add`

### PR DESCRIPTION
**Pull request by genryxy**
Closes #105 
Added reindexing packages in repo by prefix. 
Added tests for this

### CODE REVIEW

File: src/main/java/com/artipie/helm/Helm.java [hunk 1]
```diff
@@ -265,6 +277,53 @@
...
+                            final SortedSet<Key> tgzs = new TreeSet<>(Key.CMP_STRING);
+                            tgzs.addAll(keys);
+                            new AddWriter.Asto(this.storage)
+                                .addTrustfully(out, tgzs)
+                                .thenCompose(
+                                    noth -> this.moveFromTempStorageAndDelete(
+                                        tmpstrg, new Key.From(out.getFileName().toString()),
+                                        dir.get(), keyidx
+                                    )
+                                ).handle(
```
Comment (olenagerasimova) [inline src/main/java/com/artipie/helm/Helm.java:308]: @genryxy seems like is would be more correct to handle all the possible errors and remove temp dir on the most external futures chain.

**Review by olenagerasimova — CHANGES_REQUESTED** [review]
@genryxy thanks, please, check my comments

File: src/main/java/com/artipie/helm/Helm.java [hunk 2]
```diff
@@ -265,6 +277,53 @@
...
+                        .collect(Collectors.toSet())
+                ).thenCompose(
+                    keys -> {
+                        try {
+                            final CompletableFuture<Void> result = new CompletableFuture<>();
+                            final String prfx = "index-";
+                            dir.set(Files.createTempDirectory(prfx));
+                            final Path out = Files.createTempFile(dir.get(), prfx, "-out.yaml");
+                            final Storage tmpstrg = new FileStorage(dir.get());
+                            final SortedSet<Key> tgzs = new TreeSet<>(Key.CMP_STRING);
```
[the remark this answers is not in the document]
Comment (genryxy) [reply src/main/java/com/artipie/helm/Helm.java:299]: @olenagerasimova As I understand creating temporary directory is no an immediate operation, therefore it should be placed in an asynchronous block (according to [this comment](https://github.com/artipie/helm-adapter/pull/112#discussion_r622187235)). I think that update won't start if an error will be occurred during creating a temporary directory because it would go to `catch` block after throwing such exception

File: src/main/java/com/artipie/helm/Helm.java (hunk 1 above)
Comment (genryxy) [reply src/main/java/com/artipie/helm/Helm.java:308]: @olenagerasimova probably to move block with creation temp dir to the first section of section? So, if an exception is occurred during creation of temporary directory, it won't start reading all keys from storage and filtering them.

**Comment by genryxy** [comment]
@olenagerasimova could you please take a look

**Review by olenagerasimova — CHANGES_REQUESTED** [review]

**Comment by olenagerasimova** [comment]
@genryxy hm, please, check my comments, I do not see any answers or changes...

File: src/main/java/com/artipie/helm/Helm.java [hunk 3]
```diff
@@ -280,48 +280,58 @@
...
-                                            result.completeExceptionally(thr);
-                                        }
-                                        return null;
-                                    }
-                                );
-                            return result;
-                        } catch (final IOException exc) {
-                            throw new ArtipieIOException(exc);
+            final CompletableFuture<Void> result = new CompletableFuture<>();
+            CompletableFuture.supplyAsync(
```
Comment (olenagerasimova) [inline src/main/java/com/artipie/helm/Helm.java:287]: @genryxy sorry, I was wrong to suggest `supplyAsync`, `runAsync` is better here, it returns `Void`, there should not be any need for `thenCompose(Function.identity())`

**Review by olenagerasimova — CHANGES_REQUESTED** [review]
@genryxy thanks, please check one suggestion to simplify code

**Review by olenagerasimova — APPROVED** [review]
@genryxy thanks, approving
